env:
  global:
    - CC_TEST_REPORTER_ID=95cd2d1bb4cc5d3141d456773f8640471e77a915141e1a35a9e810ac77ba25fc
language: python
dist: xenial
python:
  - '3.7'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pytest --cov imgload
  - coverage xml
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  on:
    tags: true
    branch: master
  provider: pypi
  user: __token__
  password:
    secure: gV4VGSdWjElp6AFw71Zj/kCIB0zLBcHoPrlR6z/zrswsY0BBnBaB1XpxEfXcfOFJ1zpAdTP/qSpTHdTzx/F2j0NLb4tXAyg+ZJkkLkuRs7U17Gt2EEFNpiq1S5asBGpg3fPLMf/g0wwpfftztbz/8xISzL8mUCMB4v8FHsq85I/EC9cmfmakE2gyR4NqXeuVZ/3WNXLitFumfyHgiFx5QUYcMG8XX8EDktjpuxOOl8+d0X0eEij5efsshYTAmJ+0LpKUKOj4AVReNKbrGjzIArvTc4bC5xc1BRCnOJOrmbvj6FblUpvpT40qYrfX50l0cGcqp/ZS9ChbRwLPfak0GGsCwPA/HxSWmRSGvWHySO4rubf4JSznwdr/dVP7Ua0I9qp+ZO+D8y8e7gnjtitZIJ5wRrY7IDi4cwMx6RaC20GjlXbRzEJXDXIyaBtQKawsyrgXvNfMUzPdfYuBVjtndlVWaXRInB9WFNjrvHj5KaVmAkYe28kMDn44rHmhtY9EBHDk56fLKX1NPmQpKXX8wRW49pr4q/y4udriESd+G1kfUhpKRqlpopqF9B7fdY0Gu9o/yJq5lh+lP472uNSVKB5Xm5T1fR8pI+nLVsPnkFXqxvoeLWKZlF3il1mqWQd8k3v2cbjpaoB+/F/bNk/jrHmO9IwcjUwQmm5QDM7br3k=
